export const productsData = [
    {
        id: 1,
        name: "Apple iPhone 12",
        price: 799,
        category: "apple",
        description: "New Apple iPhone 12 (64GB, Blue) [Locked] + Carrier Subscription",
        image: "https://images-na.ssl-images-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg",
    },
    {
        id: 2,
        name: "Apple iPhone 11",
        price: 599,
        category: "apple",
        description: "Apple iPhone 11, 64GB, Black - Fully Unlocked (Renewed)",
        image: "https://images-na.ssl-images-amazon.com/images/I/51kGDXeFZKL._AC_SL1024_.jpg",
    },
    {
        id: 3,
        name: "Apple iPhone SE",
        price: 399,
        category: "apple",
        description: "Apple iPhone SE, 64GB, Black - Fully Unlocked (Renewed Premium)",
        image: "https://images-na.ssl-images-amazon.com/images/I/71YlH-4MUQL._AC_SL1500_.jpg",
    },
    {
        id: 4,
        name: "Apple iPhone XR",
        price: 499,
        category: "apple",
        description: "Apple iPhone XR, 64GB, Black - Fully Unlocked (Renewed Premium)",
        image: "https://images-na.ssl-images-amazon.com/images/I/51g+3T7fcsL._AC_SL1024_.jpg",
    },
    {
        id: 5,
        name: "Apple iPhone XS",
        price: 599,
        category: "apple",
        description: "Apple iPhone XS, 64GB, Space Gray - Fully Unlocked (Renewed Premium)",
        image: "https://images-na.ssl-images-amazon.com/images/I/71YlH-4MUQL._AC_SL1500_.jpg",
    },
    {
        id: 6,
        name: "Apple iPhone 8",
        price: 399,
        category: "apple",
        description: "Apple iPhone 8, 64GB, Space Gray - Fully Unlocked (Renewed Premium)",
        image: "https://images-na.ssl-images-amazon.com/images"
    },
    {
        id: 7,
        name: "Samsung Galaxy S20",
        price: 799,
        category: "samsung",
        description: "Samsung Galaxy S20 FE 5G | Factory Unlocked Android Cell Phone | 128 GB | US Version Smartphone | Pro-Grade Camera, 30X Space Zoom, Night Mode | Cloud Lavender",
        image: "https://images-na.ssl-images-amazon.com/images/I/71z2dc%2B%2BnrL._AC_SL1500_.jpg",
    },
    {
        id: 8,
        name: "Samsung Galaxy S10",
        price: 599,
        category: "samsung",
        description: "Samsung Galaxy S10+ Plus 128GB+8GB RAM SM-G975F/DS Dual Sim 6.4\" LTE Factory Unlocked Smartphone International Model (Prism Black) (Renewed)",
        image: "https://images-na.ssl-images-amazon.com/images/I/61v%2Bk9%2BwJbL._AC_SL1000_.jpg",
    },
    {
        id: 9,
        name: "Samsung Galaxy S9",
        price: 399,
        category: "samsung",
        description: "Samsung Galaxy S9, 64GB, Lilac Purple - Fully Unlocked (Renewed)",
        image: "https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SL1500_.jpg",
    },
    {
        id: 10,
        name: "Samsung Galaxy S8",
        price: 299,
        category: "samsung",
        description: "Samsung Galaxy S8, 64GB, Midnight Black - Fully Unlocked (Renewed)",
        image: "https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SL1500_.jpg",
    },
    {
        id: 11,
        name: "Samsung Galaxy S7",
        price: 199,
        category: "samsung",
        description: "Samsung Galaxy S7 Edge, 32GB, Black - Fully Unlocked (Renewed)",
        image: "https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SL1500_.jpg",
    },
    // samsung 
]